import {MigrationInterface, QueryRunner} from "typeorm";

export class MoveToEventGeneric1643481177228 implements MigrationInterface {
    name = 'MoveToEventGeneric1643481177228'

    public async up(queryRunner: QueryRunner): Promise<void> {
        await queryRunner.query(`CREATE TABLE "tag" ("id" SERIAL NOT NULL, "createdAt" TIMESTAMP NOT NULL DEFAULT now(), "updatedAt" TIMESTAMP NOT NULL DEFAULT now(), "title" character varying NOT NULL, "color" character varying NOT NULL, CONSTRAINT "UQ_ea660f2baf9c3f3141d7c2ef531" UNIQUE ("title"), CONSTRAINT "PK_8e4052373c579afc1471f526760" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE TABLE "project_tags_tag" ("projectId" integer NOT NULL, "tagId" integer NOT NULL, CONSTRAINT "PK_3215f280f961a2c7bea05565512" PRIMARY KEY ("projectId", "tagId"))`);
        await queryRunner.query(`CREATE INDEX "IDX_5438ba7df067895391b6f9f415" ON "project_tags_tag" ("projectId") `);
        await queryRunner.query(`CREATE INDEX "IDX_041c5496afa04d41bbafb5c98f" ON "project_tags_tag" ("tagId") `);
        await queryRunner.query(`CREATE TABLE "talk_tags_tag" ("talkId" integer NOT NULL, "tagId" integer NOT NULL, CONSTRAINT "PK_3165373009fc3a91b7465d18c58" PRIMARY KEY ("talkId", "tagId"))`);
        await queryRunner.query(`CREATE INDEX "IDX_fb741ca9af8d6436e783c2f8ae" ON "talk_tags_tag" ("talkId") `);
        await queryRunner.query(`CREATE INDEX "IDX_29473ab0fdbba427f4b9172014" ON "talk_tags_tag" ("tagId") `);
        await queryRunner.query(`CREATE TABLE "tutorial_tags_tag" ("tutorialId" integer NOT NULL, "tagId" integer NOT NULL, CONSTRAINT "PK_95cec0607c814268fcd6388efb2" PRIMARY KEY ("tutorialId", "tagId"))`);
        await queryRunner.query(`CREATE INDEX "IDX_e50789c44aa746e6f4e2507597" ON "tutorial_tags_tag" ("tutorialId") `);
        await queryRunner.query(`CREATE INDEX "IDX_48b344dac7057328a01d7d208c" ON "tutorial_tags_tag" ("tagId") `);
        await queryRunner.query(`CREATE TABLE "course_tags_tag" ("courseId" integer NOT NULL, "tagId" integer NOT NULL, CONSTRAINT "PK_8981acfc6f4c94276d19e467470" PRIMARY KEY ("courseId", "tagId"))`);
        await queryRunner.query(`CREATE INDEX "IDX_2e1274b2f40e354196a48ecd69" ON "course_tags_tag" ("courseId") `);
        await queryRunner.query(`CREATE INDEX "IDX_843133fef3f7894d9779811338" ON "course_tags_tag" ("tagId") `);
        await queryRunner.query(`ALTER TABLE "project" RENAME COLUMN "joinButton" TO "joinable"`);
        await queryRunner.query(`ALTER TABLE "project" DROP COLUMN "difficulty"`);
        await queryRunner.query(`ALTER TABLE "project" RENAME COLUMN "cover" TO "previewImg"`);
        await queryRunner.query(`ALTER TABLE "project" RENAME COLUMN "redirect" TO "redirectUrl"`);
        await queryRunner.query(`ALTER TABLE "talk" RENAME COLUMN "joinButton" TO "joinable"`);
        await queryRunner.query(`ALTER TABLE "talk" RENAME COLUMN "cover" TO "previewImg"`);
        await queryRunner.query(`ALTER TABLE "talk" RENAME COLUMN "redirect" TO "redirectUrl"`);
        await queryRunner.query(`ALTER TABLE "tutorial" RENAME COLUMN "joinButton" TO "joinable"`);
        await queryRunner.query(`ALTER TABLE "tutorial" DROP COLUMN "difficulty"`);
        await queryRunner.query(`ALTER TABLE "tutorial" RENAME COLUMN "cover" TO "previewImg"`);
        await queryRunner.query(`ALTER TABLE "tutorial" RENAME COLUMN "redirect" TO "redirectUrl"`);
        await queryRunner.query(`ALTER TABLE "course" RENAME COLUMN "joinButton" TO "joinable"`);
        await queryRunner.query(`ALTER TABLE "course" DROP COLUMN "difficulty"`);
        await queryRunner.query(`ALTER TABLE "course" RENAME COLUMN "cover" TO "previewImg"`);
        await queryRunner.query(`ALTER TABLE "course" RENAME COLUMN "redirect" TO "redirectUrl"`);
        await queryRunner.query(`ALTER TABLE "project" ALTER COLUMN "previewImg" SET DEFAULT ''`);
        await queryRunner.query(`ALTER TABLE "project" ADD "iconImg" character varying NOT NULL DEFAULT ''`);
        await queryRunner.query(`ALTER TABLE "project" ADD "coverImg" character varying NOT NULL DEFAULT ''`);
        await queryRunner.query(`ALTER TABLE "project" ALTER COLUMN "redirectUrl" SET DEFAULT ''`);
        await queryRunner.query(`ALTER TABLE "project" ALTER COLUMN "joinable" SET DEFAULT false`);
        await queryRunner.query(`ALTER TABLE "talk" ALTER COLUMN "previewImg" SET DEFAULT ''`);
        await queryRunner.query(`ALTER TABLE "talk" ADD "iconImg" character varying NOT NULL DEFAULT ''`);
        await queryRunner.query(`ALTER TABLE "talk" ADD "coverImg" character varying NOT NULL DEFAULT ''`);
        await queryRunner.query(`ALTER TABLE "talk" ALTER COLUMN "redirectUrl" SET DEFAULT ''`);
        await queryRunner.query(`ALTER TABLE "talk" ALTER COLUMN "joinable" SET DEFAULT false`);
        await queryRunner.query(`ALTER TABLE "tutorial" ALTER COLUMN "previewImg" SET DEFAULT ''`);
        await queryRunner.query(`ALTER TABLE "tutorial" ADD "iconImg" character varying NOT NULL DEFAULT ''`);
        await queryRunner.query(`ALTER TABLE "tutorial" ADD "coverImg" character varying NOT NULL DEFAULT ''`);
        await queryRunner.query(`ALTER TABLE "tutorial" ALTER COLUMN "redirectUrl" SET DEFAULT ''`);
        await queryRunner.query(`ALTER TABLE "tutorial" ALTER COLUMN "joinable" SET DEFAULT false`);
        await queryRunner.query(`ALTER TABLE "course" ALTER COLUMN "previewImg" SET DEFAULT ''`);
        await queryRunner.query(`ALTER TABLE "course" ADD "iconImg" character varying NOT NULL DEFAULT ''`);
        await queryRunner.query(`ALTER TABLE "course" ADD "coverImg" character varying NOT NULL DEFAULT ''`);
        await queryRunner.query(`ALTER TABLE "course" ALTER COLUMN "redirectUrl" SET DEFAULT ''`);
        await queryRunner.query(`ALTER TABLE "course" ALTER COLUMN "joinable" SET DEFAULT false`);
        await queryRunner.query(`ALTER TABLE "project" ADD CONSTRAINT "UQ_ff02a2000fd89c2c3fd98f3f444" UNIQUE ("shortName")`);
        await queryRunner.query(`ALTER TABLE "project" ALTER COLUMN "description" SET DEFAULT ''`);
        await queryRunner.query(`ALTER TABLE "talk" ADD CONSTRAINT "UQ_6030ee898320c794a2e79d3d1c0" UNIQUE ("shortName")`);
        await queryRunner.query(`ALTER TABLE "talk" ALTER COLUMN "description" SET DEFAULT ''`);
        await queryRunner.query(`ALTER TABLE "tutorial" ADD CONSTRAINT "UQ_a8a853f5e24060fcfc0eaf01ef1" UNIQUE ("shortName")`);
        await queryRunner.query(`ALTER TABLE "tutorial" ALTER COLUMN "description" SET DEFAULT ''`);
        await queryRunner.query(`ALTER TABLE "course" ADD CONSTRAINT "UQ_05371c17774785ba88ce565f6fa" UNIQUE ("shortName")`);
        await queryRunner.query(`ALTER TABLE "course" ALTER COLUMN "description" SET DEFAULT ''`);
        await queryRunner.query(`ALTER TABLE "project_tags_tag" ADD CONSTRAINT "FK_5438ba7df067895391b6f9f4157" FOREIGN KEY ("projectId") REFERENCES "project"("id") ON DELETE CASCADE ON UPDATE CASCADE`);
        await queryRunner.query(`ALTER TABLE "project_tags_tag" ADD CONSTRAINT "FK_041c5496afa04d41bbafb5c98f6" FOREIGN KEY ("tagId") REFERENCES "tag"("id") ON DELETE CASCADE ON UPDATE CASCADE`);
        await queryRunner.query(`ALTER TABLE "talk_tags_tag" ADD CONSTRAINT "FK_fb741ca9af8d6436e783c2f8ae4" FOREIGN KEY ("talkId") REFERENCES "talk"("id") ON DELETE CASCADE ON UPDATE CASCADE`);
        await queryRunner.query(`ALTER TABLE "talk_tags_tag" ADD CONSTRAINT "FK_29473ab0fdbba427f4b9172014d" FOREIGN KEY ("tagId") REFERENCES "tag"("id") ON DELETE CASCADE ON UPDATE CASCADE`);
        await queryRunner.query(`ALTER TABLE "tutorial_tags_tag" ADD CONSTRAINT "FK_e50789c44aa746e6f4e25075972" FOREIGN KEY ("tutorialId") REFERENCES "tutorial"("id") ON DELETE CASCADE ON UPDATE CASCADE`);
        await queryRunner.query(`ALTER TABLE "tutorial_tags_tag" ADD CONSTRAINT "FK_48b344dac7057328a01d7d208c3" FOREIGN KEY ("tagId") REFERENCES "tag"("id") ON DELETE CASCADE ON UPDATE CASCADE`);
        await queryRunner.query(`ALTER TABLE "course_tags_tag" ADD CONSTRAINT "FK_2e1274b2f40e354196a48ecd696" FOREIGN KEY ("courseId") REFERENCES "course"("id") ON DELETE CASCADE ON UPDATE CASCADE`);
        await queryRunner.query(`ALTER TABLE "course_tags_tag" ADD CONSTRAINT "FK_843133fef3f7894d97798113382" FOREIGN KEY ("tagId") REFERENCES "tag"("id") ON DELETE CASCADE ON UPDATE CASCADE`);
    }

    public async down(queryRunner: QueryRunner): Promise<void> {
        await queryRunner.query(`ALTER TABLE "course_tags_tag" DROP CONSTRAINT "FK_843133fef3f7894d97798113382"`);
        await queryRunner.query(`ALTER TABLE "course_tags_tag" DROP CONSTRAINT "FK_2e1274b2f40e354196a48ecd696"`);
        await queryRunner.query(`ALTER TABLE "tutorial_tags_tag" DROP CONSTRAINT "FK_48b344dac7057328a01d7d208c3"`);
        await queryRunner.query(`ALTER TABLE "tutorial_tags_tag" DROP CONSTRAINT "FK_e50789c44aa746e6f4e25075972"`);
        await queryRunner.query(`ALTER TABLE "talk_tags_tag" DROP CONSTRAINT "FK_29473ab0fdbba427f4b9172014d"`);
        await queryRunner.query(`ALTER TABLE "talk_tags_tag" DROP CONSTRAINT "FK_fb741ca9af8d6436e783c2f8ae4"`);
        await queryRunner.query(`ALTER TABLE "project_tags_tag" DROP CONSTRAINT "FK_041c5496afa04d41bbafb5c98f6"`);
        await queryRunner.query(`ALTER TABLE "project_tags_tag" DROP CONSTRAINT "FK_5438ba7df067895391b6f9f4157"`);
        await queryRunner.query(`ALTER TABLE "course" ALTER COLUMN "description" DROP DEFAULT`);
        await queryRunner.query(`ALTER TABLE "course" DROP CONSTRAINT "UQ_05371c17774785ba88ce565f6fa"`);
        await queryRunner.query(`ALTER TABLE "tutorial" ALTER COLUMN "description" DROP DEFAULT`);
        await queryRunner.query(`ALTER TABLE "tutorial" DROP CONSTRAINT "UQ_a8a853f5e24060fcfc0eaf01ef1"`);
        await queryRunner.query(`ALTER TABLE "talk" ALTER COLUMN "description" DROP DEFAULT`);
        await queryRunner.query(`ALTER TABLE "talk" DROP CONSTRAINT "UQ_6030ee898320c794a2e79d3d1c0"`);
        await queryRunner.query(`ALTER TABLE "project" ALTER COLUMN "description" DROP DEFAULT`);
        await queryRunner.query(`ALTER TABLE "project" DROP CONSTRAINT "UQ_ff02a2000fd89c2c3fd98f3f444"`);
        await queryRunner.query(`ALTER TABLE "course" DROP COLUMN "joinable"`);
        await queryRunner.query(`ALTER TABLE "course" DROP COLUMN "redirectUrl"`);
        await queryRunner.query(`ALTER TABLE "course" DROP COLUMN "coverImg"`);
        await queryRunner.query(`ALTER TABLE "course" DROP COLUMN "iconImg"`);
        await queryRunner.query(`ALTER TABLE "course" DROP COLUMN "previewImg"`);
        await queryRunner.query(`ALTER TABLE "tutorial" DROP COLUMN "joinable"`);
        await queryRunner.query(`ALTER TABLE "tutorial" DROP COLUMN "redirectUrl"`);
        await queryRunner.query(`ALTER TABLE "tutorial" DROP COLUMN "coverImg"`);
        await queryRunner.query(`ALTER TABLE "tutorial" DROP COLUMN "iconImg"`);
        await queryRunner.query(`ALTER TABLE "tutorial" DROP COLUMN "previewImg"`);
        await queryRunner.query(`ALTER TABLE "talk" DROP COLUMN "joinable"`);
        await queryRunner.query(`ALTER TABLE "talk" DROP COLUMN "redirectUrl"`);
        await queryRunner.query(`ALTER TABLE "talk" DROP COLUMN "coverImg"`);
        await queryRunner.query(`ALTER TABLE "talk" DROP COLUMN "iconImg"`);
        await queryRunner.query(`ALTER TABLE "talk" DROP COLUMN "previewImg"`);
        await queryRunner.query(`ALTER TABLE "project" DROP COLUMN "joinable"`);
        await queryRunner.query(`ALTER TABLE "project" DROP COLUMN "redirectUrl"`);
        await queryRunner.query(`ALTER TABLE "project" DROP COLUMN "coverImg"`);
        await queryRunner.query(`ALTER TABLE "project" DROP COLUMN "iconImg"`);
        await queryRunner.query(`ALTER TABLE "project" DROP COLUMN "previewImg"`);
        await queryRunner.query(`ALTER TABLE "course" ADD "redirect" character varying NOT NULL DEFAULT ''`);
        await queryRunner.query(`ALTER TABLE "course" ADD "cover" character varying NOT NULL`);
        await queryRunner.query(`ALTER TABLE "course" ADD "difficulty" character varying NOT NULL`);
        await queryRunner.query(`ALTER TABLE "course" ADD "joinButton" boolean NOT NULL DEFAULT false`);
        await queryRunner.query(`ALTER TABLE "tutorial" ADD "redirect" character varying NOT NULL DEFAULT ''`);
        await queryRunner.query(`ALTER TABLE "tutorial" ADD "cover" character varying NOT NULL`);
        await queryRunner.query(`ALTER TABLE "tutorial" ADD "difficulty" character varying NOT NULL`);
        await queryRunner.query(`ALTER TABLE "tutorial" ADD "joinButton" boolean NOT NULL DEFAULT false`);
        await queryRunner.query(`ALTER TABLE "talk" ADD "redirect" character varying NOT NULL DEFAULT ''`);
        await queryRunner.query(`ALTER TABLE "talk" ADD "cover" character varying NOT NULL`);
        await queryRunner.query(`ALTER TABLE "talk" ADD "joinButton" boolean NOT NULL DEFAULT false`);
        await queryRunner.query(`ALTER TABLE "project" ADD "redirect" character varying NOT NULL DEFAULT ''`);
        await queryRunner.query(`ALTER TABLE "project" ADD "cover" character varying NOT NULL`);
        await queryRunner.query(`ALTER TABLE "project" ADD "difficulty" character varying NOT NULL`);
        await queryRunner.query(`ALTER TABLE "project" ADD "joinButton" boolean NOT NULL DEFAULT false`);
        await queryRunner.query(`DROP INDEX "public"."IDX_843133fef3f7894d9779811338"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_2e1274b2f40e354196a48ecd69"`);
        await queryRunner.query(`DROP TABLE "course_tags_tag"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_48b344dac7057328a01d7d208c"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_e50789c44aa746e6f4e2507597"`);
        await queryRunner.query(`DROP TABLE "tutorial_tags_tag"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_29473ab0fdbba427f4b9172014"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_fb741ca9af8d6436e783c2f8ae"`);
        await queryRunner.query(`DROP TABLE "talk_tags_tag"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_041c5496afa04d41bbafb5c98f"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_5438ba7df067895391b6f9f415"`);
        await queryRunner.query(`DROP TABLE "project_tags_tag"`);
        await queryRunner.query(`DROP TABLE "tag"`);
    }

}
